---
title: "Comparison of spatial and non-spatial tuning"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}
p_load(sf, mapview, sperrorest, randomForestSRC)
```

```{r}
data(ecuador)
fo <- slides ~ dem + slope + hcurv + vcurv + log.carea + cslope
```

# Spatial tuning

```{r}
sp_tuning <- sptune_rf(fo, ecuador, nfold = 5, step_factor = 2,
                       rf_fun = "rfsrc", partition_fun = "partition_kmeans")
```

```{r}
plot_hyper_rf(sp_tuning)
```


# non-spatial tuning

```{r}
non_sp_tuning <- sptune_rf(fo, ecuador, nfold = 5,
                           rf_fun = "rfsrc", partition_fun = "partition_cv")
```


# Spatial cross-validation

```{r}
sp_tuning_spcv <- sperrorest(fo, ecuador, 
                             smp_fun = partition_kmeans, 
                             smp_args = list(repetition = 100, nfold = 5),
                             pred_args = list(probabilities = TRUE),
                             par_args = list(par_mode = "apply", par_units = 25))
```

